name: Ahk2Exe
description: GitHub Action to compile AutoHotKey scripts using Ahk2Exe
author: nekocodeX

inputs:
  in:
    description: The path or file name of the AutoHotKey script to compile
    required: true
  out:
    description: The path or file name of the compiled executable (by default, an executable of the same name will be created in the path of the AutoHotKey script specified by the "in" parameter)
    required: false
    default: ''
  icon:
    description: The icon of the executable file is specified
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install Scoop
      shell: powershell
      run: |
        try{get-command scoop -ErrorAction Stop}catch{
        iwr -useb get.scoop.sh | iex
        scoop bucket add extras
        }

    - name: Add to environment variables
      shell: powershell
      run: Write-Output ('Path=' + $Env:SystemDrive + '\Windows\System32' + ';' + $Env:UserProfile + '\scoop\shims') >> $Env:GITHUB_ENV

    - name: Install AutoHotkey
      shell: powershell
      run: scoop install autohotkey
    - name: Ahk2Exe
      shell: powershell
      run: |
        $ErrorActionPreference = 'Stop'
        Resolve-Path '${{inputs.in}}'
        Write-Host "Generating exe"
        Get-Command ahk2exe
        tree C:\Users\runneradmin\scoop\apps\autohotkey\current\Compiler\ /F
        
        if (('${{inputs.in}}' -ne '') -and ('${{inputs.out}}' -ne '') -and ('${{inputs.icon}}' -ne '')) {
          ahk2exe /in '${{inputs.in}}' /out '${{inputs.out}}' /icon '${{inputs.icon}}' /silent
        } elseif (('${{inputs.in}}' -ne '') -and ('${{inputs.out}}' -ne '')) {
          ahk2exe /in '${{inputs.in}}' /out '${{inputs.out}}' /silent
        } elseif (('${{inputs.in}}' -ne '') -and ('${{inputs.icon}}' -ne '')) {
          ahk2exe /in '${{inputs.in}}' /icon '${{inputs.icon}}' /silent
        } elseif ('${{inputs.in}}' -ne '') {
          ahk2exe /in (Resolve-Path '${{inputs.in}}').Path /silent
        } else {
          throw 'There are no required parameters'
        }
        tree \ /F
        Resolve-Path '${{inputs.in}}'.replace('.ahk','.exe')
branding:
  color: green
  icon: terminal
