name: Ahk2Exe
description: GitHub Action to compile AutoHotKey scripts using Ahk2Exe
author: nekocodeX

inputs:
  in:
    description: The path or file name of the AutoHotKey script to compile
    required: true
  out:
    description: The path or file name of the compiled executable (by default, an executable of the same name will be created in the path of the AutoHotKey script specified by the "in" parameter)
    required: false
    default: ''
  icon:
    description: The icon of the executable file is specified
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Choco help
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install autohotkey -y


    - name: Add to environment variables
      shell: powershell
      run: Write-Output ('Path=' + $Env:SystemDrive + '\Windows\System32' + ';' + $ENV:ProgramFiles + '\AutoHotkey\Compiler') >> $Env:GITHUB_ENV

    - name: Install AutoHotkey
      shell: powershell
      run: choco install autohotkey
    - name: Ahk2Exe
      shell: powershell
      run: |
        $ErrorActionPreference = 'Stop'
        Resolve-Path '${{inputs.in}}'
        Write-Host "Generating exe"
        Get-Command ahk2exe
        tree C:\Users\runneradmin\scoop\shims\ /F
        tree C:\Users\runneradmin\scoop\apps\autohotkey\current\Compiler /F
        if (('${{inputs.in}}' -ne '') -and ('${{inputs.out}}' -ne '') -and ('${{inputs.icon}}' -ne '')) {
          ahk2exe /in '${{inputs.in}}' /out '${{inputs.out}}' /icon '${{inputs.icon}}' /silent
        } elseif (('${{inputs.in}}' -ne '') -and ('${{inputs.out}}' -ne '')) {
          ahk2exe /in '${{inputs.in}}' /out '${{inputs.out}}' /silent
        } elseif (('${{inputs.in}}' -ne '') -and ('${{inputs.icon}}' -ne '')) {
          ahk2exe /in '${{inputs.in}}' /icon '${{inputs.icon}}' /silent
        } elseif ('${{inputs.in}}' -ne '') {
          ahk2exe /in (Resolve-Path '${{inputs.in}}').Path /silent
        } else {
          throw 'There are no required parameters'
        }
        tree \ /F
        Resolve-Path '${{inputs.in}}'.replace('.ahk','.exe')
branding:
  color: green
  icon: terminal
